### ISSUE TITLE
/listings/discriminaotry page isn't working anymore

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#114]
Needs to be looked into

**Comment by mzagaja** [comment]
Does this happen when there are listings in the database? The error I get is basically complaining there is no discriminatory listings so it's trying to call methods off nil. If I comment out the template it renders fine. So it needs to find at least one discriminatory listing or someone should add a conditional to account for the lack of any discriminatory listings in the template.
