### ISSUE TITLE
Create a list of discriminatory works

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#19]
Create a list of discriminatory language that could make a listing illegal.

**Comment by tbarto** [comment]
Here are some keywords that I brainstormed from the MA website that has lots of discriminatory topics:
http://www.mass.gov/ago/consumer-resources/your-rights/civil-rights/housing/housing-discrimination.html

### Religions
christianity, christian, islam, muslim, catholicism, catholic, hinduism, hindu, buddhism, buddhist, sikhism, sikh, seventh-day adventists, latter day saints, mormonism, mormon, judaism, jewish, jew

### Sex
male, female, transgender

### Age
old, young, college

### Handicap/Disability
disabled, handicapped 

### Marital Status
single, married, couple

### Sexual orientation
gay, straight, bisexual

### Children
no children

### Public Assistance
section 8, section eight, public assistance

### Lead Paint
lead paint

### Veteran Status
veteran, military
