### ISSUE TITLE
Create a list of posts base on a filter

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#81]
Create a list of listings using:
filter by date / date range
filter by phrase / keyword

Send the result back to the client. May want to just send meta data first

**Comment by jmartini** [comment]
Two functions have been added to listing.rb already that can return this info:
check_phrase() in PR #68 
date_range() in PR #104

**Comment by kfili** [comment]
@smithWEBtek and @Joshhw solved this issue as part of issue #87
