### ISSUE TITLE
Update site map

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#85]
Need to have a better navbar.

Sitemap:

/Home

/Tools
&nbsp;&nbsp;/Track Changes
&nbsp;&nbsp;/Stats

/Postings
&nbsp;&nbsp;/All Posts
&nbsp;&nbsp;/Discriminatory Posts

/Contact

**Comment by kfili** [comment]
Site map updated by @SamiraMansouri  and there are two issues open for fixing the problems with listings/discriminatory and /contact
