### ISSUE TITLE
Get cached stats

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#86]
The front end will send a token to the server to get the stats.

Token examples:  "3m", "6m", "1y", "all"

Server should keep a map of {token, cached results}
The cached results should update once a date. We can do this when a user requests the results or just have a cron job to do it at midnight.

When the server gets the token it should find the results and then send it back to the client

**Comment by kfili** [comment]
Wireframe and diagram of functionality of getting cached stats:
![img_20170523_205050](https://cloud.githubusercontent.com/assets/22824118/26609958/90ee6c6e-4572-11e7-8212-68611cb0821b.jpg)
