### ISSUE TITLE
Track changes widget

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/legalhousing#92]
Create a widget that will show data based on the changes from 1 time period to the next based on the housing listings. It should include

- Number of listings from date 1
- Number of listings from date 2
- Number of discriminatory listings from date 1
- Number of discriminatory listings from date 2
- Number of listings changes (How many total less listings were there from date 1 to date 2)
- Percent of listings chagnes (What was the percent change from date 2 to date 2)

**Comment by AlexMerritt** [comment]
Here is a link to how to do a month picker in bootstrap 
http://jsfiddle.net/brunodd/k5zookLt/20/

**Comment by jmartini** [comment]
Backend completed in in PR #111
