### ISSUE TITLE
Seeds.rb refers to missing bad_words.csv file

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/legalhousing#97]
When I attempt to run rails `db:setup` I get:

`Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/mzagaja/GitHub/legalhousing/lib/seeds/bad_words.csv`

**Comment by Joshhw** [comment]
This was due to changes within the repo to include bad_words.csv. I'll attach the file in the slack chat for it.

**Comment by mzagaja** [comment]
@Joshhw The best way would be to submit a PR that removes .csv from the .gitignore file and then include the file in a pull request.
